node-id: <MSG_CENTER_NODE_ID>
name: rtfm-msg-center
log-level: trace
aws-region: <AWS_REGION>
aws-access-key: <AWS_ACCESS_KEY>
aws-secret: <AWS_SECRET_ACCESS_KEY>
aws-sns-topic-arn: <AWS_SNS_TOPIC>
heartbeat-interval: 1000
